### A. Getting Started With Python & Data Analysis
#### Data is the core of data science, hence, scoping and collecting the right data for a project is very crucial to achieving the required results. A complete Data Science Pipeline involves 
#### 1. Data Scoping
#### 2. Data Review
#### 3. Feature engineering 
#### 4. Feature Review 
#### 5. Model Selection and review 
#### 6. Model Evaluation and Insights
#### 7. Interaction Production 
#### 8. Feedback

#### Conducting Exploratory Data Analysis (EDA) on the cleaned data using visualisations and statistical methods gives a quick insight into the various patterns and relationships between features in the dataset. Modelling involves using statistical and machine learning methods for classifying and clustering the processed data to create predictive models. Several evaluation methods are employed to compare the performance of these models and continuously improve before a final model is selected.

#### For the most part, the data science pipeline is not a linear process; it’s instead an iterative process.

#### Data can be presented in different forms such as CSV, JSON, Excel files, database etc. Python is very efficient in processing and wrangling most data types. The libraries Include Numpy, Pandas , Matplotlib , Scikit-Learn and TensorFlow.

#### Jupyter notebook is an interactive web environment that supports many programming languages including Python and R, allowing for explanatory text, images and visualisation.

### B. Introduction to NumPy & Creating Arrays.

#### NumPy is a library that has ndarray as its basic data structure used to handle arrays and matrices. A NumPy array has a grid of values all of which are of the same data type, mostly integers and floats. These arrays can also be created from Python lists.

In [2]:
#Importing Numpy library 
import numpy as np 

arr = [1,2,3,4]  #Created a simple list and assigned it to a variable 

print (arr)
print (type(arr))

[1, 2, 3, 4]
<class 'list'>


In [3]:
#Converting the list arr to an Array 
a = np.array(arr)

print(type(a)) # The type of ellemnt which is a numpy array

print(a.shape) # The shape of the array which is (4,0)

print(a.dtype) # The type of data in the array which is int

print(a.ndim) # The number of dimension which is 1

<class 'numpy.ndarray'>
(4,)
int32
1


In [4]:
# Lets create a two dimentional array
b= np.array([[1,2,3,4],[5,6,7,8]])

print(b.shape) # The shape of the array where the first dimension has 2 elements and the second has 4.

print(b.ndim) # The dimension of the array

(2, 4)
2


#### There are also some inbuilt functions that can be used to initialize numpy which include empty(), zeros(), ones(), full(), random.random().

In [5]:
zero_array = np.zeros(5) #Takes the number of zeros as an argument 

print(zero_array)

[0. 0. 0. 0. 0.]


In [6]:
empty_array =np.empty([2,2]) #Takes an array or integer as an argument

print(empty_array)

[[-1.10380189e-282  2.52625418e+286]
 [ 6.65259379e-301  2.21764760e-301]]


In [7]:
one_array = np.ones([2,3])

one_array2 = np.ones(5)

print(one_array)
print('-----------')
print(one_array2)

[[1. 1. 1.]
 [1. 1. 1.]]
-----------
[1. 1. 1. 1. 1.]


In [8]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [9]:
np.full((2,2),[1,2])

array([[1, 2],
       [1, 2]])

In [10]:
np.random.random((2,3))

array([[0.12813459, 0.25392002, 0.31635468],
       [0.49618729, 0.77583433, 0.46724096]])

### C. Intra-operability of Arrays and Scalars.

#### This allows for batch arithmetic operations on the arrays by applying the operator elementwise. Similarly, scalars are also propagated element-wise across an array. For arrays with different sizes, it is impossible to perform element-wise operations instead; numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1

In [11]:
c = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
d = np.array([[2.0,4.0,8.0],[1.0,3.0,6.0]])

print(c)
print(d)

[[1. 2. 3.]
 [4. 5. 6.]]
[[2. 4. 8.]
 [1. 3. 6.]]


In [12]:
c+d #Addition operator 

array([[ 3.,  6., 11.],
       [ 5.,  8., 12.]])

In [13]:
c-d # subtraction operator

array([[-1., -2., -5.],
       [ 3.,  2.,  0.]])

In [14]:
d/5 #Divide

array([[0.4, 0.8, 1.6],
       [0.2, 0.6, 1.2]])

In [15]:
c**2 #Power

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### D. Indexing With Arrays & Using Arrays for Data Processing

In [16]:
a[2]

3

In [17]:
b[0,0] #Enter list 0 and give me the element on index zero

1

In [18]:
b[1,2] #Enter the list 1 and give me the second element 

7

#### Array Slicing 

In [20]:
d

array([[2., 4., 8.],
       [1., 3., 6.]])

In [21]:
d[1, :2]

array([1., 3.])

In [23]:
e=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[11,12,13,14]])
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 12, 13, 14]])

In [24]:
e[:3 , :2] # Means give me index 0 to 2 list and their inddex 0 to 1 elemnets 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [25]:
e.sum() # sum of all elements

128

In [26]:
e[1].sum()

26

In [27]:
e[1].mean() #Mean of elemtns in index 0 (a list)

6.5

In [32]:
e.std()  #look up the formula for standard deviation

4.0

In [29]:
e[1].min() # Prints the minimun value

5

In [31]:
np.corrcoef(e)  #Browse more on Correlation and how it works

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### E. File input and output with Arrays 

#### Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. This can also be done with text files with text files using loadtxt() and savetxt().

In [33]:
np.save('testfile', np.array([[1, 2, 3], [4, 5, 6]]))

In [34]:
np.load('testfile.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
from io import StringIO

newstring = StringIO("0 1\n2 3")

np.loadtxt(newstring)

array([[0., 1.],
       [2., 3.]])

## Pandas - So Much More Than A Cute Animal

#### Pandas is a library  built on Numpy which is used for data manipulation, with other ways of indexing other than integers. Series, DataFrame, and index are the basic data structures in this library.  Series in pandas can be referred to as a one dimensional array with homogenous elements of different types somewhat similar to numpy arrays; however, it can be indexed differently with specified descriptive labels or integers.

In [39]:
import pandas as pd

days =pd.Series(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
days

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
dtype: object

In [41]:
#You convert a numpy to a dataframe 
new_days = np.array(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])

new_df_days = pd.Series (new_days)

new_df_days

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
dtype: object

In [43]:
#Using Strings as Indexes

days = pd.Series(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],['a','b','c','d','e','f','g'])
days

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
f     Saturday
g       Sunday
dtype: object

In [44]:
#parcing a Dictionary

days = pd.Series({'a':'Monday','b':'Tuesday','c':'Wednesday','d':'Thursday','e':'Friday','f':'Saturday','g':'Sunday'})
days

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
f     Saturday
g       Sunday
dtype: object

### Data Frames

In [46]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [47]:
#Creating out of a dictionary
df_dict ={
        'Country':['Nigeria','Kenya','Togo','Ghana'],
         'Capital':['Abuja','Nairobi','Lome','Accra'],
         'Population':[10000,8500,3500,1200],
         'Age':[60,50,70,80]
         }

df = pd.DataFrame(df_dict, index = [2,4,6,8])

df

Country  Capital  Population  Age
2  Nigeria    Abuja       10000   60
4    Kenya  Nairobi        8500   50
6     Togo     Lome        3500   70
8    Ghana    Accra        1200   80

In [48]:
#Creating out of lists
df_list = [['Nigeria','Kenya','Togo','Ghana'],
           ['Abuja','Nairobi','Lome','Accra'],
          [10000,8500,3500,1200],
          [60,50,70,80]
          ]
df1 = pd.DataFrame(df_list, columns = ['Country','Capital','Population','Age'], index = [2,4,6,8])

df1

Country  Capital Population    Age
2  Nigeria    Kenya       Togo  Ghana
4    Abuja  Nairobi       Lome  Accra
6    10000     8500       3500   1200
8       60       50         70     80

#### at, iat, iloc and loc are accessors used to retrieve data in dataframes. iloc selects values from the rows and columns by using integer index to locate positions, while loc selects rows or columns using labels. at and iat are used to retrieve single values such that at uses the column and row labels and iat uses indices.

In [49]:
df.iloc[3]

Country       Ghana
Capital       Accra
Population     1200
Age              80
Name: 8, dtype: object

In [51]:
df.loc[6]

Country       Togo
Capital       Lome
Population    3500
Age             70
Name: 6, dtype: object

In [52]:
df['Capital']

2      Abuja
4    Nairobi
6       Lome
8      Accra
Name: Capital, dtype: object

In [53]:
df['Population'].sum()

23200

In [54]:
df['Country'].count()

4

In [55]:
df.mean()

Population    5800.0
Age             65.0
dtype: float64

In [56]:
df.describe()

Population        Age
count      4.000000   4.000000
mean    5800.000000  65.000000
std     4138.437708  12.909944
min     1200.000000  50.000000
25%     2925.000000  57.500000
50%     6000.000000  65.000000
75%     8875.000000  72.500000
max    10000.000000  80.000000

#### The missing data enigma: Importance, types and handling missing data.

In [57]:
df

Country  Capital  Population  Age
2  Nigeria    Abuja       10000   60
4    Kenya  Nairobi        8500   50
6     Togo     Lome        3500   70
8    Ghana    Accra        1200   80

In [60]:
df.at[2,'Country']=np.nan #Lets assign a null value to nigeria in the datframe

In [61]:
df

Country  Capital  Population  Age
2     NaN    Abuja       10000   60
4   Kenya  Nairobi        8500   50
6    Togo     Lome        3500   70
8   Ghana    Accra        1200   80

In [62]:
df.isnull()

Country  Capital  Population    Age
2     True    False       False  False
4    False    False       False  False
6    False    False       False  False
8    False    False       False  False

In [65]:
df(df.isnull())

TypeError: 'DataFrame' object is not callable

In [64]:
df

Country  Capital  Population  Age
2     NaN    Abuja       10000   60
4   Kenya  Nairobi        8500   50
6    Togo     Lome        3500   70
8   Ghana    Accra        1200   80